import type { LandRecord } from "./types";

/**
 * Illustrative 7/12-style index for search UX.
 * Official signed extracts remain on MahaBhulekh (Maharashtra Revenue).
 */
export const SAMPLE_LAND_RECORDS: LandRecord[] = [
  {
    id: "pn-hav-001",
    surveyNo: "142/3",
    owners: [{ fullName: "Ramesh Shankar Patil", surname: "Patil" }],
    district: "Pune",
    taluka: "Haveli",
    village: "Wagholi",
    post: "Wagholi",
    areaHa: 1.24,
    landType: "Jirayat",
    crop: "Sugarcane",
    khataNo: "218",
  },
  {
    id: "pn-hav-002",
    surveyNo: "88/1",
    owners: [
      { fullName: "Sunita Ashok Jadhav", surname: "Jadhav" },
      { fullName: "Ashok Maruti Jadhav", surname: "Jadhav" },
    ],
    district: "Pune",
    taluka: "Haveli",
    village: "Hadapsar",
    post: "Hadapsar",
    areaHa: 0.62,
    landType: "Bagayat",
    crop: "Vegetables",
    khataNo: "91",
  },
  {
    id: "pn-bar-003",
    surveyNo: "215",
    owners: [{ fullName: "Vijay Kondiba More", surname: "More" }],
    district: "Pune",
    taluka: "Baramati",
    village: "Baramati",
    post: "Baramati",
    areaHa: 3.05,
    landType: "Bagayat",
    crop: "Sugarcane",
    khataNo: "540",
  },
  {
    id: "pn-jun-004",
    surveyNo: "47/2",
    owners: [{ fullName: "Sanjay Baban Kulkarni", surname: "Kulkarni" }],
    district: "Pune",
    taluka: "Junnar",
    village: "Narayangaon",
    post: "Narayangaon",
    areaHa: 0.88,
    landType: "Jirayat",
    crop: "Onion",
    khataNo: "112",
  },
  {
    id: "ns-nip-005",
    surveyNo: "301/6",
    owners: [{ fullName: "Nitin Dilip Pawar", surname: "Pawar" }],
    district: "Nashik",
    taluka: "Niphad",
    village: "Pimpalgaon Baswant",
    post: "Pimpalgaon Baswant",
    areaHa: 2.1,
    landType: "Bagayat",
    crop: "Grapes",
    khataNo: "778",
  },
  {
    id: "ns-mal-006",
    surveyNo: "19",
    owners: [{ fullName: "Farooq Ahmed Shaikh", surname: "Shaikh" }],
    district: "Nashik",
    taluka: "Malegaon",
    village: "Malegaon",
    post: "Malegaon",
    areaHa: 0.45,
    landType: "Jirayat",
    crop: "Cotton",
    khataNo: "330",
  },
  {
    id: "ns-sin-007",
    surveyNo: "66/4",
    owners: [{ fullName: "Rekha Suresh Shinde", surname: "Shinde" }],
    district: "Nashik",
    taluka: "Sinnar",
    village: "Sinnar",
    post: "Sinnar",
    areaHa: 1.55,
    landType: "Jirayat",
    crop: "Onion",
    khataNo: "201",
  },
  {
    id: "ah-san-008",
    surveyNo: "120/1",
    owners: [{ fullName: "Ganesh Popat Deshmukh", surname: "Deshmukh" }],
    district: "Ahilyanagar",
    taluka: "Sangamner",
    village: "Sangamner",
    post: "Sangamner",
    areaHa: 4.2,
    landType: "Bagayat",
    crop: "Sugarcane",
    khataNo: "64",
  },
  {
    id: "ah-rah-009",
    surveyNo: "55",
    owners: [{ fullName: "Mahesh Vitthal Thorat", surname: "Thorat" }],
    district: "Ahilyanagar",
    taluka: "Rahuri",
    village: "Rahuri",
    post: "Rahuri",
    areaHa: 1.9,
    landType: "Jirayat",
    crop: "Jowar",
    khataNo: "145",
  },
  {
    id: "kl-kar-010",
    surveyNo: "9/7",
    owners: [{ fullName: "Prakash Dattatray Chavan", surname: "Chavan" }],
    district: "Kolhapur",
    taluka: "Karvir",
    village: "Kolhapur",
    post: "Kolhapur",
    areaHa: 0.73,
    landType: "Bagayat",
    crop: "Sugarcane",
    khataNo: "812",
  },
  {
    id: "kl-hat-011",
    surveyNo: "188",
    owners: [{ fullName: "Anil Maruti Magar", surname: "Magar" }],
    district: "Kolhapur",
    taluka: "Hatkanangle",
    village: "Ichalkaranji",
    post: "Ichalkaranji",
    areaHa: 0.31,
    landType: "Class II",
    crop: "Cotton",
    khataNo: "44",
  },
  {
    id: "sg-mir-012",
    surveyNo: "72/2",
    owners: [{ fullName: "Suresh Appa Patil", surname: "Patil" }],
    district: "Sangli",
    taluka: "Miraj",
    village: "Sangli",
    post: "Sangli",
    areaHa: 2.44,
    landType: "Bagayat",
    crop: "Sugarcane",
    khataNo: "509",
  },
  {
    id: "sg-wal-013",
    surveyNo: "41",
    owners: [{ fullName: "Savitri Ramesh Yadav", surname: "Yadav" }],
    district: "Sangli",
    taluka: "Walwa",
    village: "Islampur",
    post: "Islampur",
    areaHa: 1.12,
    landType: "Jirayat",
    crop: "Groundnut",
    khataNo: "276",
  },
  {
    id: "st-kar-014",
    surveyNo: "203/5",
    owners: [{ fullName: "Deepak Hanumant Bhosale", surname: "Bhosale" }],
    district: "Satara",
    taluka: "Karad",
    village: "Karad",
    post: "Karad",
    areaHa: 1.67,
    landType: "Bagayat",
    crop: "Sugarcane",
    khataNo: "388",
  },
  {
    id: "st-wai-015",
    surveyNo: "14",
    owners: [{ fullName: "Meena Sharad Joshi", surname: "Joshi" }],
    district: "Satara",
    taluka: "Wai",
    village: "Wai",
    post: "Wai",
    areaHa: 0.58,
    landType: "Jirayat",
    crop: "Rice",
    khataNo: "97",
  },
  {
    id: "sl-pan-016",
    surveyNo: "501",
    owners: [{ fullName: "Balasaheb Namdeo Kale", surname: "Kale" }],
    district: "Solapur",
    taluka: "Pandharpur",
    village: "Pandharpur",
    post: "Pandharpur",
    areaHa: 5.1,
    landType: "Jirayat",
    crop: "Jowar",
    khataNo: "1201",
  },
  {
    id: "sl-bar-017",
    surveyNo: "77/3",
    owners: [{ fullName: "Laxman Popat Gaikwad", surname: "Gaikwad" }],
    district: "Solapur",
    taluka: "Barshi",
    village: "Barshi",
    post: "Barshi",
    areaHa: 2.02,
    landType: "Jirayat",
    crop: "Cotton",
    khataNo: "654",
  },
  {
    id: "rt-dap-018",
    surveyNo: "28/1",
    owners: [{ fullName: "Sadanand Vasant Sawant", surname: "Sawant" }],
    district: "Ratnagiri",
    taluka: "Dapoli",
    village: "Dapoli",
    post: "Dapoli",
    areaHa: 0.95,
    landType: "Bagayat",
    crop: "Mango",
    khataNo: "183",
  },
  {
    id: "rt-chi-019",
    surveyNo: "112",
    owners: [{ fullName: "Pradip Sitaram Gujar", surname: "Gujar" }],
    district: "Ratnagiri",
    taluka: "Chiplun",
    village: "Chiplun",
    post: "Chiplun",
    areaHa: 0.4,
    landType: "Jirayat",
    crop: "Rice",
    khataNo: "55",
  },
  {
    id: "sd-mal-020",
    surveyNo: "6/2",
    owners: [{ fullName: "Ajit Ramesh Rane", surname: "Rane" }],
    district: "Sindhudurg",
    taluka: "Malvan",
    village: "Tarkarli",
    post: "Tarkarli",
    areaHa: 0.22,
    landType: "Bagayat",
    crop: "Coconut",
    khataNo: "19",
  },
  {
    id: "sd-dev-061",
    surveyNo: "37/2",
    owners: [
      { fullName: "Suresh Anant Limaye", surname: "Limaye" },
      { fullName: "Prakash Anant Limaye", surname: "Limaye" },
    ],
    district: "Sindhudurg",
    taluka: "Devgad",
    village: "Dabhole",
    post: "Dabhole",
    areaHa: 1.18,
    landType: "Bagayat",
    crop: "Mango",
    khataNo: "142",
  },
  {
    id: "sd-dev-062",
    surveyNo: "51",
    owners: [{ fullName: "Meena Vilas Limaye", surname: "Limaye" }],
    district: "Sindhudurg",
    taluka: "Devgad",
    village: "Dabhole",
    post: "Dabhole",
    areaHa: 0.64,
    landType: "Jirayat",
    crop: "Rice",
    khataNo: "143",
  },
  {
    id: "rg-pan-021",
    surveyNo: "350/8",
    owners: [{ fullName: "Kavita Nitin Mhatre", surname: "Mhatre" }],
    district: "Raigad",
    taluka: "Panvel",
    village: "Kharghar",
    post: "Kharghar",
    areaHa: 0.18,
    landType: "Class II",
    khataNo: "902",
  },
  {
    id: "rg-ali-022",
    surveyNo: "45",
    owners: [{ fullName: "Suresh Pandurang Naik", surname: "Naik" }],
    district: "Raigad",
    taluka: "Alibag",
    village: "Alibag",
    post: "Alibag",
    areaHa: 0.7,
    landType: "Bagayat",
    crop: "Rice",
    khataNo: "210",
  },
  {
    id: "th-bhi-023",
    surveyNo: "99/4",
    owners: [{ fullName: "Imran Yusuf Khan", surname: "Khan" }],
    district: "Thane",
    taluka: "Bhiwandi",
    village: "Bhiwandi",
    post: "Bhiwandi",
    areaHa: 0.35,
    landType: "Class II",
    khataNo: "441",
  },
  {
    id: "th-kal-024",
    surveyNo: "12",
    owners: [{ fullName: "Prashant Dilip Bhoir", surname: "Bhoir" }],
    district: "Thane",
    taluka: "Kalyan",
    village: "Titwala",
    post: "Titwala",
    areaHa: 0.5,
    landType: "Jirayat",
    crop: "Rice",
    khataNo: "128",
  },
  {
    id: "pg-vas-025",
    surveyNo: "210/1",
    owners: [{ fullName: "Sunil Vasant Tandel", surname: "Tandel" }],
    district: "Palghar",
    taluka: "Vasai",
    village: "Virar",
    post: "Virar",
    areaHa: 0.27,
    landType: "Class II",
    khataNo: "67",
  },
  {
    id: "cs-pai-026",
    surveyNo: "134",
    owners: [{ fullName: "Rahul Madhukar Jadhav", surname: "Jadhav" }],
    district: "Chhatrapati Sambhajinagar",
    taluka: "Paithan",
    village: "Paithan",
    post: "Paithan",
    areaHa: 3.4,
    landType: "Bagayat",
    crop: "Sugarcane",
    khataNo: "733",
  },
  {
    id: "cs-sil-027",
    surveyNo: "58/2",
    owners: [{ fullName: "Ashwini Santosh Pathan", surname: "Pathan" }],
    district: "Chhatrapati Sambhajinagar",
    taluka: "Sillod",
    village: "Sillod",
    post: "Sillod",
    areaHa: 1.05,
    landType: "Jirayat",
    crop: "Cotton",
    khataNo: "290",
  },
  {
    id: "jl-amb-028",
    surveyNo: "81",
    owners: [{ fullName: "Dattatray Baburao Kharat", surname: "Kharat" }],
    district: "Jalna",
    taluka: "Ambad",
    village: "Ambad",
    post: "Ambad",
    areaHa: 2.75,
    landType: "Jirayat",
    crop: "Soybean",
    khataNo: "418",
  },
  {
    id: "bd-amb-029",
    surveyNo: "167/3",
    owners: [{ fullName: "Siddharth Ramesh Solanke", surname: "Solanke" }],
    district: "Beed",
    taluka: "Ambajogai",
    village: "Ambajogai",
    post: "Ambajogai",
    areaHa: 1.48,
    landType: "Jirayat",
    crop: "Cotton",
    khataNo: "156",
  },
  {
    id: "lt-nil-030",
    surveyNo: "220",
    owners: [{ fullName: "Pravin Shivaji Biradar", surname: "Biradar" }],
    district: "Latur",
    taluka: "Nilanga",
    village: "Nilanga",
    post: "Nilanga",
    areaHa: 3.8,
    landType: "Jirayat",
    crop: "Tur",
    khataNo: "870",
  },
  {
    id: "nd-kin-031",
    surveyNo: "39/1",
    owners: [{ fullName: "Shankar Rao Rathod", surname: "Rathod" }],
    district: "Nanded",
    taluka: "Kinwat",
    village: "Kinwat",
    post: "Kinwat",
    areaHa: 2.2,
    landType: "Jirayat",
    crop: "Cotton",
    khataNo: "311",
  },
  {
    id: "pb-jin-032",
    surveyNo: "94",
    owners: [{ fullName: "Vaishali Kishor Deshmukh", surname: "Deshmukh" }],
    district: "Parbhani",
    taluka: "Jintur",
    village: "Jintur",
    post: "Jintur",
    areaHa: 1.33,
    landType: "Bagayat",
    crop: "Wheat",
    khataNo: "204",
  },
  {
    id: "hg-bas-033",
    surveyNo: "17/5",
    owners: [{ fullName: "Nagesh Vitthal Jadhav", surname: "Jadhav" }],
    district: "Hingoli",
    taluka: "Basmath",
    village: "Basmath",
    post: "Basmath",
    areaHa: 0.9,
    landType: "Jirayat",
    crop: "Soybean",
    khataNo: "88",
  },
  {
    id: "dh-osh-034",
    surveyNo: "260",
    owners: [{ fullName: "Hanumant Shankar Mane", surname: "Mane" }],
    district: "Dharashiv",
    taluka: "Tuljapur",
    village: "Tuljapur",
    post: "Tuljapur",
    areaHa: 4.55,
    landType: "Jirayat",
    crop: "Jowar",
    khataNo: "1002",
  },
  {
    id: "ak-ako-035",
    surveyNo: "71/2",
    owners: [{ fullName: "Milind Prakash Thakur", surname: "Thakur" }],
    district: "Akola",
    taluka: "Akot",
    village: "Akot",
    post: "Akot",
    areaHa: 1.7,
    landType: "Jirayat",
    crop: "Cotton",
    khataNo: "365",
  },
  {
    id: "am-war-036",
    surveyNo: "108",
    owners: [{ fullName: "Sandip Ramesh Wankhede", surname: "Wankhede" }],
    district: "Amravati",
    taluka: "Warud",
    village: "Warud",
    post: "Warud",
    areaHa: 2.6,
    landType: "Bagayat",
    crop: "Orange",
    khataNo: "521",
  },
  {
    id: "bl-kha-037",
    surveyNo: "33/6",
    owners: [{ fullName: "Pramod Gajanan Ingle", surname: "Ingle" }],
    district: "Buldhana",
    taluka: "Khamgaon",
    village: "Khamgaon",
    post: "Khamgaon",
    areaHa: 1.15,
    landType: "Jirayat",
    crop: "Cotton",
    khataNo: "147",
  },
  {
    id: "ws-man-038",
    surveyNo: "52",
    owners: [{ fullName: "Ravindra Suresh Ade", surname: "Ade" }],
    district: "Washim",
    taluka: "Mangrulpir",
    village: "Mangrulpir",
    post: "Mangrulpir",
    areaHa: 2.05,
    landType: "Jirayat",
    crop: "Soybean",
    khataNo: "233",
  },
  {
    id: "yv-pus-039",
    surveyNo: "190/4",
    owners: [{ fullName: "Umesh Madhukar Rathod", surname: "Rathod" }],
    district: "Yavatmal",
    taluka: "Pusad",
    village: "Pusad",
    post: "Pusad",
    areaHa: 3.15,
    landType: "Jirayat",
    crop: "Cotton",
    khataNo: "690",
  },
  {
    id: "ng-saon-040",
    surveyNo: "24/1",
    owners: [{ fullName: "Anita Sanjay Meshram", surname: "Meshram" }],
    district: "Nagpur",
    taluka: "Saoner",
    village: "Saoner",
    post: "Saoner",
    areaHa: 0.85,
    landType: "Bagayat",
    crop: "Vegetables",
    khataNo: "176",
  },
  {
    id: "ng-ram-041",
    surveyNo: "63",
    owners: [{ fullName: "Kishor Baban Lonare", surname: "Lonare" }],
    district: "Nagpur",
    taluka: "Ramtek",
    village: "Ramtek",
    post: "Ramtek",
    areaHa: 1.4,
    landType: "Jirayat",
    crop: "Rice",
    khataNo: "259",
  },
  {
    id: "wd-hin-042",
    surveyNo: "11/3",
    owners: [{ fullName: "Sachin Vitthal Dhande", surname: "Dhande" }],
    district: "Wardha",
    taluka: "Hinganghat",
    village: "Hinganghat",
    post: "Hinganghat",
    areaHa: 1.95,
    landType: "Jirayat",
    crop: "Cotton",
    khataNo: "402",
  },
  {
    id: "ch-war-043",
    surveyNo: "275",
    owners: [{ fullName: "Manoj Ramesh Madavi", surname: "Madavi" }],
    district: "Chandrapur",
    taluka: "Warora",
    village: "Warora",
    post: "Warora",
    areaHa: 2.3,
    landType: "Jirayat",
    crop: "Cotton",
    khataNo: "588",
  },
  {
    id: "bh-tum-044",
    surveyNo: "8",
    owners: [{ fullName: "Pramila Dilip Borkar", surname: "Borkar" }],
    district: "Bhandara",
    taluka: "Tumsar",
    village: "Tumsar",
    post: "Tumsar",
    areaHa: 0.68,
    landType: "Bagayat",
    crop: "Rice",
    khataNo: "73",
  },
  {
    id: "go-tir-045",
    surveyNo: "46/2",
    owners: [{ fullName: "Rohit Anil Rahangdale", surname: "Rahangdale" }],
    district: "Gondia",
    taluka: "Tirora",
    village: "Tirora",
    post: "Tirora",
    areaHa: 1.02,
    landType: "Jirayat",
    crop: "Rice",
    khataNo: "134",
  },
  {
    id: "gc-arm-046",
    surveyNo: "3/1",
    owners: [{ fullName: "Bhaskar Soma Pungati", surname: "Pungati" }],
    district: "Gadchiroli",
    taluka: "Armori",
    village: "Armori",
    post: "Armori",
    areaHa: 0.55,
    landType: "Gairan",
    khataNo: "21",
  },
  {
    id: "jg-bhu-047",
    surveyNo: "159/7",
    owners: [{ fullName: "Yogesh Prakash Patil", surname: "Patil" }],
    district: "Jalgaon",
    taluka: "Bhusawal",
    village: "Bhusawal",
    post: "Bhusawal",
    areaHa: 0.92,
    landType: "Bagayat",
    crop: "Banana",
    khataNo: "347",
  },
  {
    id: "jg-jam-048",
    surveyNo: "84",
    owners: [{ fullName: "Smita Rajendra Mahajan", surname: "Mahajan" }],
    district: "Jalgaon",
    taluka: "Jamner",
    village: "Jamner",
    post: "Jamner",
    areaHa: 1.6,
    landType: "Jirayat",
    crop: "Cotton",
    khataNo: "265",
  },
  {
    id: "dh-shi-049",
    surveyNo: "27/4",
    owners: [{ fullName: "Vikas Ashok Girase", surname: "Girase" }],
    district: "Dhule",
    taluka: "Shirpur",
    village: "Shirpur",
    post: "Shirpur",
    areaHa: 2.8,
    landType: "Bagayat",
    crop: "Cotton",
    khataNo: "612",
  },
  {
    id: "nu-sha-050",
    surveyNo: "61",
    owners: [{ fullName: "Kamalabai Motiram Valvi", surname: "Valvi" }],
    district: "Nandurbar",
    taluka: "Shahada",
    village: "Shahada",
    post: "Shahada",
    areaHa: 1.25,
    landType: "Jirayat",
    crop: "Jowar",
    khataNo: "98",
  },
  {
    id: "pn-khe-051",
    surveyNo: "410/2",
    owners: [{ fullName: "Amit Suresh Patil", surname: "Patil" }],
    district: "Pune",
    taluka: "Khed",
    village: "Chakan",
    post: "Chakan",
    areaHa: 0.48,
    landType: "Class II",
    khataNo: "755",
  },
  {
    id: "pn-shi-052",
    surveyNo: "95",
    owners: [{ fullName: "Swapnil Ramesh Jadhav", surname: "Jadhav" }],
    district: "Pune",
    taluka: "Shirur",
    village: "Ranjangaon",
    post: "Ranjangaon",
    areaHa: 2.15,
    landType: "Jirayat",
    crop: "Onion",
    khataNo: "428",
  },
  {
    id: "ns-bag-053",
    surveyNo: "178/3",
    owners: [{ fullName: "Priya Mahesh Kulkarni", surname: "Kulkarni" }],
    district: "Nashik",
    taluka: "Baglan",
    village: "Lasalgaon",
    post: "Lasalgaon",
    areaHa: 1.08,
    landType: "Bagayat",
    crop: "Onion",
    khataNo: "319",
  },
  {
    id: "ah-kop-054",
    surveyNo: "232",
    owners: [{ fullName: "Rohini Sunil Shinde", surname: "Shinde" }],
    district: "Ahilyanagar",
    taluka: "Kopargaon",
    village: "Kopargaon",
    post: "Kopargaon",
    areaHa: 3.6,
    landType: "Bagayat",
    crop: "Sugarcane",
    khataNo: "881",
  },
  {
    id: "kl-shi-055",
    surveyNo: "16/1",
    owners: [{ fullName: "Vivek Anandrao Patil", surname: "Patil" }],
    district: "Kolhapur",
    taluka: "Shirol",
    village: "Jaysingpur",
    post: "Jaysingpur",
    areaHa: 1.22,
    landType: "Bagayat",
    crop: "Sugarcane",
    khataNo: "273",
  },
  {
    id: "sl-akl-056",
    surveyNo: "140",
    owners: [{ fullName: "Nilesh Bapu Jagtap", surname: "Jagtap" }],
    district: "Solapur",
    taluka: "Malshiras",
    village: "Akluj",
    post: "Akluj",
    areaHa: 2.9,
    landType: "Bagayat",
    crop: "Sugarcane",
    khataNo: "560",
  },
  {
    id: "rt-guh-057",
    surveyNo: "5",
    owners: [{ fullName: "Deepali Hemant Chavan", surname: "Chavan" }],
    district: "Ratnagiri",
    taluka: "Guhagar",
    village: "Velneshwar",
    post: "Velneshwar",
    areaHa: 0.36,
    landType: "Bagayat",
    crop: "Mango",
    khataNo: "42",
  },
  {
    id: "cs-vai-058",
    surveyNo: "89/2",
    owners: [{ fullName: "Sagar Popat Pawar", surname: "Pawar" }],
    district: "Chhatrapati Sambhajinagar",
    taluka: "Vaijapur",
    village: "Vaijapur",
    post: "Vaijapur",
    areaHa: 2.45,
    landType: "Jirayat",
    crop: "Cotton",
    khataNo: "477",
  },
  {
    id: "lt-udg-059",
    surveyNo: "201/8",
    owners: [{ fullName: "Ashok Shivaji Mane", surname: "Mane" }],
    district: "Latur",
    taluka: "Udgir",
    village: "Udgir",
    post: "Udgir",
    areaHa: 1.85,
    landType: "Jirayat",
    crop: "Tur",
    khataNo: "392",
  },
  {
    id: "am-mor-060",
    surveyNo: "74",
    owners: [{ fullName: "Pooja Ravi Deshmukh", surname: "Deshmukh" }],
    district: "Amravati",
    taluka: "Morshi",
    village: "Morshi",
    post: "Morshi",
    areaHa: 1.5,
    landType: "Bagayat",
    crop: "Orange",
    khataNo: "228",
  },
];
