import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const data = [
  {
    name: "Ahilyanagar",
    aliases: ["Ahmednagar", "Ahmadnagar"],
    talukas: [
      { name: "Ahilyanagar", villages: [["Ahilyanagar", "Ahilyanagar"], ["Savedi", "Savedi"], ["Kedgaon", "Kedgaon"], ["Nagardeole", "Nagardeole"]] },
      { name: "Sangamner", villages: [["Sangamner", "Sangamner"], ["Ashwi Bk", "Ashwi"], ["Ghulewadi", "Ghulewadi"], ["Nimgaon Jali", "Nimgaon"]] },
      { name: "Shrirampur", villages: [["Shrirampur", "Shrirampur"], ["Belapur", "Belapur"], ["Taklibhan", "Taklibhan"]] },
      { name: "Kopargaon", villages: [["Kopargaon", "Kopargaon"], ["Yesgaon", "Yesgaon"], ["Kolgaon", "Kolgaon"]] },
      { name: "Rahuri", villages: [["Rahuri", "Rahuri"], ["Vambori", "Vambori"], ["Taharabad", "Taharabad"]] },
      { name: "Nevasa", villages: [["Nevasa", "Nevasa"], ["Bhende", "Bhende"], ["Ghodegaon", "Ghodegaon"]] },
      { name: "Pathardi", villages: [["Pathardi", "Pathardi"], ["Tisgaon", "Tisgaon"], ["Karanji", "Karanji"]] },
      { name: "Shevgaon", villages: [["Shevgaon", "Shevgaon"], ["Bodhegaon", "Bodhegaon"]] },
      { name: "Parner", villages: [["Parner", "Parner"], ["Supa", "Supa"], ["Alkuti", "Alkuti"]] },
      { name: "Akole", villages: [["Akole", "Akole"], ["Rajur", "Rajur"], ["Bramhanwada", "Bramhanwada"]] },
    ],
  },
  {
    name: "Akola",
    talukas: [
      { name: "Akola", villages: ["Akola", "Shivani", "Murtizapur Road"] },
      { name: "Akot", villages: ["Akot", "Dahihanda", "Alegaon"] },
      { name: "Balapur", villages: ["Balapur", "Vyalla", "Patur Nandapur"] },
      { name: "Murtizapur", villages: ["Murtizapur", "Kamargaon", "Karanja Lad"] },
      { name: "Patur", villages: ["Patur", "Channi", "Umara"] },
      { name: "Telhara", villages: ["Telhara", "Adgaon", "Hiwarkhed"] },
      { name: "Barshitakli", villages: ["Barshitakli", "Pinjar", "Donad"] },
    ],
  },
  {
    name: "Amravati",
    talukas: [
      { name: "Amravati", villages: ["Amravati", "Badnera", "Naya Akola", "Walgaon"] },
      { name: "Achalpur", villages: ["Achalpur", "Paratwada", "Pathrot"] },
      { name: "Anjangaon Surji", villages: ["Anjangaon Surji", "Kokarda", "Yeoda"] },
      { name: "Chandur Bazar", villages: ["Chandur Bazar", "Tiosa", "Assegaon"] },
      { name: "Chandur Railway", villages: ["Chandur Railway", "Dhamangaon"] },
      { name: "Daryapur", villages: ["Daryapur", "Amla", "Nanded Bk"] },
      { name: "Dhamangaon Railway", villages: ["Dhamangaon Railway", "Nimbhora"] },
      { name: "Morshi", villages: ["Morshi", "Warud", "Benoda"] },
      { name: "Warud", villages: ["Warud", "Jarud", "Loni"] },
      { name: "Bhatkuli", villages: ["Bhatkuli", "Nandgaon Peth"] },
      { name: "Nandgaon Khandeshwar", villages: ["Nandgaon Khandeshwar", "Shirasgaon"] },
      { name: "Teosa", villages: ["Teosa", "Kurha"] },
      { name: "Dharni", villages: ["Dharni", "Chikhaldara"] },
      { name: "Chikhaldara", villages: ["Chikhaldara", "Semadoh"] },
    ],
  },
  {
    name: "Beed",
    talukas: [
      { name: "Beed", villages: ["Beed", "Pali", "Neknoor", "Limba Ganesh"] },
      { name: "Georai", villages: ["Georai", "Umapur", "Rakshasbhuvan"] },
      { name: "Majalgaon", villages: ["Majalgaon", "Talkhed", "Dindrud"] },
      { name: "Ambajogai", villages: ["Ambajogai", "Morewadi", "Yogeshwari"] },
      { name: "Kaij", villages: ["Kaij", "Dharmapuri", "Yusuf Wadgaon"] },
      { name: "Parli", villages: ["Parli", "Nagapur"] },
      { name: "Ashti", villages: ["Ashti", "Kada", "Shirur Kasar"] },
      { name: "Patoda", villages: ["Patoda", "Dhanora", "Ghargaon"] },
      { name: "Shirur Kasar", villages: ["Shirur Kasar"] },
      { name: "Wadwani", villages: ["Wadwani", "Chinchpur"] },
      { name: "Dharur", villages: ["Dharur", "Chinchwan"] },
    ],
  },
  {
    name: "Bhandara",
    talukas: [
      { name: "Bhandara", villages: ["Bhandara", "Pauni", "Shahapur"] },
      { name: "Tumsar", villages: ["Tumsar", "Sihora", "Mohadi"] },
      { name: "Pauni", villages: ["Pauni", "Adyal", "Navegaon"] },
      { name: "Mohadi", villages: ["Mohadi", "Andhalgaon"] },
      { name: "Sakoli", villages: ["Sakoli", "Sangadi", "Sendurwafa"] },
      { name: "Lakhani", villages: ["Lakhani", "Pohara"] },
      { name: "Lakhandur", villages: ["Lakhandur", "Dighori"] },
    ],
  },
  {
    name: "Buldhana",
    talukas: [
      { name: "Buldhana", villages: ["Buldhana", "Dhad", "Malvihir"] },
      { name: "Chikhli", villages: ["Chikhli", "Amdapur", "Hatni"] },
      { name: "Deulgaon Raja", villages: ["Deulgaon Raja", "Sultanpur"] },
      { name: "Jalgaon Jamod", villages: ["Jalgaon Jamod", "Asalgaon"] },
      { name: "Khamgaon", villages: ["Khamgaon", "Nandura Road", "Shegaon"] },
      { name: "Lonar", villages: ["Lonar"] },
      { name: "Malkapur", villages: ["Malkapur", "Nimbhora"] },
      { name: "Mehkar", villages: ["Mehkar", "Dongarkhandala"] },
      { name: "Motala", villages: ["Motala", "Nandura"] },
      { name: "Nandura", villages: ["Nandura", "Wadner"] },
      { name: "Sangrampur", villages: ["Sangrampur", "Wankhed"] },
      { name: "Shegaon", villages: ["Shegaon", "Jalamb"] },
      { name: "Sindkhed Raja", villages: ["Sindkhed Raja", "Dusarbid"] },
    ],
  },
  {
    name: "Chandrapur",
    talukas: [
      { name: "Chandrapur", villages: ["Chandrapur", "Durgapur", "Ballarpur"] },
      { name: "Ballarpur", villages: ["Ballarpur", "Visapur"] },
      { name: "Bhadravati", villages: ["Bhadravati", "Chandai"] },
      { name: "Warora", villages: ["Warora", "Shegaon"] },
      { name: "Brahmapuri", villages: ["Brahmapuri", "Gangalwadi"] },
      { name: "Nagbhid", villages: ["Nagbhid", "Talodhi"] },
      { name: "Sindewahi", villages: ["Sindewahi", "Navargaon"] },
      { name: "Mul", villages: ["Mul", "Rajoli"] },
      { name: "Saoli", villages: ["Saoli", "Pathari"] },
      { name: "Gondpipri", villages: ["Gondpipri", "Pombhurna"] },
      { name: "Korpana", villages: ["Korpana"] },
      { name: "Rajura", villages: ["Rajura", "Wirur"] },
      { name: "Jiwati", villages: ["Jiwati", "Markanda"] },
      { name: "Pombhurna", villages: ["Pombhurna"] },
      { name: "Chimur", villages: ["Chimur", "Neri"] },
    ],
  },
  {
    name: "Chhatrapati Sambhajinagar",
    aliases: ["Aurangabad", "Sambhajinagar"],
    talukas: [
      { name: "Chhatrapati Sambhajinagar", villages: ["Chhatrapati Sambhajinagar", "Cidco", "Waluj", "Chikalthana"] },
      { name: "Gangapur", villages: ["Gangapur", "Waluj", "Limbe Jalgaon"] },
      { name: "Vaijapur", villages: ["Vaijapur", "Lasur", "Shivoor"] },
      { name: "Paithan", villages: ["Paithan", "Bidkin", "Pachod"] },
      { name: "Phulambri", villages: ["Phulambri"] },
      { name: "Khuldabad", villages: ["Khuldabad", "Ellora", "Verul"] },
      { name: "Kannad", villages: ["Kannad", "Nagad", "Aurala"] },
      { name: "Sillod", villages: ["Sillod", "Borsar", "Andhari"] },
      { name: "Soygaon", villages: ["Soygaon", "Banoti"] },
    ],
  },
  {
    name: "Dharashiv",
    aliases: ["Osmanabad"],
    talukas: [
      { name: "Dharashiv", villages: ["Dharashiv", "Osmanabad", "Bembli", "Terkheda"] },
      { name: "Tuljapur", villages: ["Tuljapur", "Naldurg", "Andur"] },
      { name: "Omerga", villages: ["Omerga", "Murum", "Lohara"] },
      { name: "Kallam", villages: ["Kallam", "Yermala"] },
      { name: "Paranda", villages: ["Paranda"] },
      { name: "Bhoom", villages: ["Bhoom", "Ieet"] },
      { name: "Washi", villages: ["Washi", "Pargaon"] },
      { name: "Lohara", villages: ["Lohara", "Jewali"] },
    ],
  },
  {
    name: "Dhule",
    talukas: [
      { name: "Dhule", villages: ["Dhule", "Songir", "Fagne", "Kusumba"] },
      { name: "Sakri", villages: ["Sakri", "Nizampur", "Dahivel"] },
      { name: "Shirpur", villages: ["Shirpur", "Thalner", "Arthe"] },
      { name: "Sindkheda", villages: ["Sindkheda", "Dondaicha", "Chimthane"] },
    ],
  },
  {
    name: "Gadchiroli",
    talukas: [
      { name: "Gadchiroli", villages: ["Gadchiroli", "Murumgaon", "Ambeshivani"] },
      { name: "Aheri", villages: ["Aheri", "Allapalli"] },
      { name: "Armori", villages: ["Armori", "Wadsa"] },
      { name: "Chamorshi", villages: ["Chamorshi", "Ghot"] },
      { name: "Desaiganj", villages: ["Desaiganj", "Wadsa"] },
      { name: "Dhanora", villages: ["Dhanora", "Murumgaon"] },
      { name: "Etapalli", villages: ["Etapalli", "Bhamragad"] },
      { name: "Kurkheda", villages: ["Kurkheda", "Korchi"] },
      { name: "Mulchera", villages: ["Mulchera"] },
      { name: "Sironcha", villages: ["Sironcha", "Asaralli"] },
      { name: "Bhamragad", villages: ["Bhamragad"] },
      { name: "Korchi", villages: ["Korchi"] },
    ],
  },
  {
    name: "Gondia",
    talukas: [
      { name: "Gondia", villages: ["Gondia", "Goregaon", "Fulchur"] },
      { name: "Tirora", villages: ["Tirora", "Kachewani"] },
      { name: "Goregaon", villages: ["Goregaon", "Dawaniwada"] },
      { name: "Amgaon", villages: ["Amgaon", "Thana"] },
      { name: "Salekasa", villages: ["Salekasa", "Darekasa"] },
      { name: "Sadak Arjuni", villages: ["Sadak Arjuni", "Navegaon"] },
      { name: "Arjuni Morgaon", villages: ["Arjuni Morgaon", "Navegaonbandh"] },
      { name: "Deori", villages: ["Deori", "Chichgarh"] },
    ],
  },
  {
    name: "Hingoli",
    talukas: [
      { name: "Hingoli", villages: ["Hingoli", "Narsi", "Basmat Road"] },
      { name: "Basmath", villages: ["Basmath", "Kurunda"] },
      { name: "Aundha Nagnath", villages: ["Aundha Nagnath", "Jawala Bazar"] },
      { name: "Kalamnuri", villages: ["Kalamnuri", "Sakhara"] },
      { name: "Sengaon", villages: ["Sengaon", "Hatta"] },
    ],
  },
  {
    name: "Jalgaon",
    talukas: [
      { name: "Jalgaon", villages: ["Jalgaon", "Mehrun", "Asoda", "Mamurabad"] },
      { name: "Bhusawal", villages: ["Bhusawal", "Varangaon", "Fekari"] },
      { name: "Yawal", villages: ["Yawal", "Faizpur", "Kingaon"] },
      { name: "Raver", villages: ["Raver", "Savda", "Khiroda"] },
      { name: "Chopda", villages: ["Chopda", "Adavad", "Vardi"] },
      { name: "Amalner", villages: ["Amalner", "Shendurni"] },
      { name: "Parola", villages: ["Parola", "Bahadarpur"] },
      { name: "Erandol", villages: ["Erandol", "Dharangaon"] },
      { name: "Dharangaon", villages: ["Dharangaon", "Salve"] },
      { name: "Pachora", villages: ["Pachora", "Nagardeola", "Lohara"] },
      { name: "Jamner", villages: ["Jamner", "Shendurni", "Pahur"] },
      { name: "Bodwad", villages: ["Bodwad", "Varangaon"] },
      { name: "Muktainagar", villages: ["Muktainagar", "Edlabad"] },
      { name: "Chalisgaon", villages: ["Chalisgaon", "Bhoras", "Mehunbare"] },
    ],
  },
  {
    name: "Jalna",
    talukas: [
      { name: "Jalna", villages: ["Jalna", "Ner", "Badnapur"] },
      { name: "Ambad", villages: ["Ambad", "Ghansawangi"] },
      { name: "Bhokardan", villages: ["Bhokardan", "Hasnabad"] },
      { name: "Badnapur", villages: ["Badnapur", "Dongaon"] },
      { name: "Ghansawangi", villages: ["Ghansawangi", "Rani Unchegaon"] },
      { name: "Partur", villages: ["Partur", "Ashti"] },
      { name: "Mantha", villages: ["Mantha", "Dahiphal"] },
      { name: "Jafrabad", villages: ["Jafrabad", "Sawargaon"] },
    ],
  },
  {
    name: "Kolhapur",
    talukas: [
      { name: "Karvir", villages: ["Kolhapur", "Gandhinagar", "Uchgaon", "Shiye"] },
      { name: "Hatkanangle", villages: ["Ichalkaranji", "Hatkanangle", "Rendal"] },
      { name: "Shirol", villages: ["Shirol", "Jaysingpur", "Nandani"] },
      { name: "Kagal", villages: ["Kagal", "Murgud", "Hamana"] },
      { name: "Gadhinglaj", villages: ["Gadhinglaj", "Nesari", "Kadgaon"] },
      { name: "Chandgad", villages: ["Chandgad", "Here", "Kowad"] },
      { name: "Ajara", villages: ["Ajara", "Gavase", "Madilage"] },
      { name: "Gaganbawada", villages: ["Gaganbawada", "Tavade"] },
      { name: "Bhudargad", villages: ["Gargoti", "Kadgaon", "Patgaon"] },
      { name: "Radhanagari", villages: ["Radhanagari", "Dajipur", "Rashiwade"] },
      { name: "Panhala", villages: ["Panhala", "Wathar", "Kodoli"] },
      { name: "Shahuwadi", villages: ["Shahuwadi", "Sarud", "Bambavade"] },
    ],
  },
  {
    name: "Latur",
    talukas: [
      { name: "Latur", villages: ["Latur", "Harangul", "Gangapur", "Murud"] },
      { name: "Ahmadpur", villages: ["Ahmadpur", "Kingaon", "Hadolti"] },
      { name: "Udgir", villages: ["Udgir", "Her", "Jalkot"] },
      { name: "Nilanga", villages: ["Nilanga", "Aurad Shahajani", "Kasarsirsi"] },
      { name: "Ausa", villages: ["Ausa", "Killari", "Matola"] },
      { name: "Chakur", villages: ["Chakur", "Nalegaon"] },
      { name: "Deoni", villages: ["Deoni", "Jalkot"] },
      { name: "Shirur Anantpal", villages: ["Shirur Anantpal"] },
      { name: "Renapur", villages: ["Renapur", "Pohregaon"] },
      { name: "Jalkot", villages: ["Jalkot", "Wagdari"] },
    ],
  },
  {
    name: "Mumbai City",
    aliases: ["Mumbai"],
    talukas: [
      { name: "Mumbai City", villages: [["Fort", "Fort"], ["Colaba", "Colaba"], ["Girgaon", "Girgaon"], ["Parel", "Parel"], ["Worli", "Worli"], ["Mahim", "Mahim"], ["Byculla", "Byculla"]] },
    ],
  },
  {
    name: "Mumbai Suburban",
    aliases: ["Mumbai Suburb"],
    talukas: [
      { name: "Andheri", villages: [["Andheri", "Andheri"], ["Versova", "Versova"], ["Juhu", "Juhu"], ["Vile Parle", "Vile Parle"]] },
      { name: "Borivali", villages: [["Borivali", "Borivali"], ["Kandivali", "Kandivali"], ["Dahisar", "Dahisar"], ["Malad", "Malad"]] },
      { name: "Kurla", villages: [["Kurla", "Kurla"], ["Ghatkopar", "Ghatkopar"], ["Chembur", "Chembur"], ["Bhandup", "Bhandup"], ["Mulund", "Mulund"]] },
    ],
  },
  {
    name: "Nagpur",
    talukas: [
      { name: "Nagpur Urban", villages: ["Nagpur", "Sitabuldi", "Dharampeth", "Manewada"] },
      { name: "Nagpur Rural", villages: ["Wadi", "Kanhan", "Kamptee", "Butibori"] },
      { name: "Kamptee", villages: ["Kamptee", "Kanhan", "Mahadula"] },
      { name: "Hingna", villages: ["Hingna", "Digdoh", "Wanadongri"] },
      { name: "Parseoni", villages: ["Parseoni", "Kanhan"] },
      { name: "Ramtek", villages: ["Ramtek", "Mansar", "Khindsi"] },
      { name: "Umred", villages: ["Umred", "Bhiwapur"] },
      { name: "Kuhi", villages: ["Kuhi", "Titur"] },
      { name: "Bhiwapur", villages: ["Bhiwapur", "Nagalwadi"] },
      { name: "Narkhed", villages: ["Narkhed", "Jalalkheda"] },
      { name: "Katol", villages: ["Katol", "Kondhali"] },
      { name: "Kalameshwar", villages: ["Kalameshwar", "Mohapa"] },
      { name: "Saoner", villages: ["Saoner", "Khapa", "Patansaongi"] },
      { name: "Mouda", villages: ["Mouda", "Tarsa"] },
    ],
  },
  {
    name: "Nanded",
    talukas: [
      { name: "Nanded", villages: ["Nanded", "Vazirabad", "Cidco", "Waghefala"] },
      { name: "Bhokar", villages: ["Bhokar", "Matul"] },
      { name: "Hadgaon", villages: ["Hadgaon", "Tamsa"] },
      { name: "Kinwat", villages: ["Kinwat", "Mandvi"] },
      { name: "Himayatnagar", villages: ["Himayatnagar", "Sirasgaon"] },
      { name: "Mudkhed", villages: ["Mudkhed", "Barad"] },
      { name: "Ardhapur", villages: ["Ardhapur", "Malegaon"] },
      { name: "Biloli", villages: ["Biloli", "Dharmabad"] },
      { name: "Dharmabad", villages: ["Dharmabad", "Bamni"] },
      { name: "Mukhed", villages: ["Mukhed", "Barhali"] },
      { name: "Kandhar", villages: ["Kandhar", "Pethwadaj"] },
      { name: "Loha", villages: ["Loha", "Sonkhed"] },
      { name: "Naigaon", villages: ["Naigaon", "Manjram"] },
      { name: "Deglur", villages: ["Deglur", "Mukramabad"] },
      { name: "Mahur", villages: ["Mahur", "Wanola"] },
      { name: "Umri", villages: ["Umri", "Isegaon"] },
    ],
  },
  {
    name: "Nandurbar",
    talukas: [
      { name: "Nandurbar", villages: ["Nandurbar", "Dhanora"] },
      { name: "Shahada", villages: ["Shahada", "Prakasha", "Mhasavad"] },
      { name: "Taloda", villages: ["Taloda", "Pratappur"] },
      { name: "Akkalkuwa", villages: ["Akkalkuwa", "Molgi"] },
      { name: "Akrani", villages: ["Akrani", "Dhadgaon"] },
      { name: "Navapur", villages: ["Navapur", "Chinchpada"] },
    ],
  },
  {
    name: "Nashik",
    talukas: [
      { name: "Nashik", villages: ["Nashik", "Gangapur", "Satpur", "Ambad", "Panchavati"] },
      { name: "Igatpuri", villages: ["Igatpuri", "Ghoti", "Padli"] },
      { name: "Dindori", villages: ["Dindori", "Vani", "Ozhar"] },
      { name: "Peth", villages: ["Peth", "Harsul"] },
      { name: "Trimbakeshwar", villages: ["Trimbakeshwar", "Anjaneri"] },
      { name: "Kalwan", villages: ["Kalwan", "Abhona"] },
      { name: "Deola", villages: ["Deola"] },
      { name: "Baglan", villages: ["Baglan", "Lasalgaon"] },
      { name: "Niphad", villages: ["Niphad", "Pimpalgaon Baswant", "Saikheda"] },
      { name: "Sinnar", villages: ["Sinnar", "Nandur Shingote", "Wavi"] },
      { name: "Yeola", villages: ["Yeola", "Andarsul", "Manmad"] },
      { name: "Nandgaon", villages: ["Nandgaon", "Manmad", "Pimpalgaon"] },
      { name: "Chandvad", villages: ["Chandvad", "Dugaon"] },
      { name: "Malegaon", villages: ["Malegaon", "Soygaon", "Dabhadi"] },
      { name: "Satana", villages: ["Satana", "Taharabad"] },
    ],
  },
  {
    name: "Palghar",
    talukas: [
      { name: "Palghar", villages: ["Palghar", "Boisar", "Mahim", "Kelwa"] },
      { name: "Vasai", villages: ["Vasai", "Nallasopara", "Virar", "Naigaon"] },
      { name: "Dahanu", villages: ["Dahanu", "Gholvad", "Bordi"] },
      { name: "Talasari", villages: ["Talasari", "Udhawa"] },
      { name: "Jawhar", villages: ["Jawhar"] },
      { name: "Mokhada", villages: ["Mokhada", "Khodala"] },
      { name: "Wada", villages: ["Wada", "Kudus", "Ganjad"] },
      { name: "Vikramgad", villages: ["Vikramgad", "Kasa"] },
    ],
  },
  {
    name: "Parbhani",
    talukas: [
      { name: "Parbhani", villages: ["Parbhani", "Daithana", "Pingli"] },
      { name: "Gangakhed", villages: ["Gangakhed", "Isad"] },
      { name: "Pathri", villages: ["Pathri", "Masala"] },
      { name: "Sonpeth", villages: ["Sonpeth", "Loha"] },
      { name: "Manwath", villages: ["Manwath", "Kolha"] },
      { name: "Selu", villages: ["Selu", "Dharmapuri"] },
      { name: "Jintur", villages: ["Jintur", "Charthana"] },
      { name: "Purna", villages: ["Purna", "Tadkalas"] },
      { name: "Palam", villages: ["Palam", "Banegaon"] },
    ],
  },
  {
    name: "Pune",
    talukas: [
      { name: "Haveli", villages: ["Pune", "Hadapsar", "Kharadi", "Wagholi", "Mundhwa", "Kondhwa", "Baner", "Balewadi", "Hinjewadi", "Pirangut"] },
      { name: "Pune City", villages: ["Shivajinagar", "Kothrud", "Deccan", "Camp", "Swargate"] },
      { name: "Maval", villages: ["Talegaon", "Lonavala", "Khandala", "Vadgaon"] },
      { name: "Mulshi", villages: ["Paud", "Lavasa", "Tamhini", "Pirangut"] },
      { name: "Bhor", villages: ["Bhor", "Nasrapur", "Shindewadi"] },
      { name: "Velhe", villages: ["Velhe", "Panshet"] },
      { name: "Purandar", villages: ["Saswad", "Jejuri", "Narayanpur"] },
      { name: "Baramati", villages: ["Baramati", "Morgaon", "Nira"] },
      { name: "Indapur", villages: ["Indapur", "Bhigwan", "Kalas"] },
      { name: "Daund", villages: ["Daund", "Patas", "Yawat"] },
      { name: "Shirur", villages: ["Shirur", "Ranjangaon", "Talegaon Dhamdhere"] },
      { name: "Junnar", villages: ["Junnar", "Narayangaon", "Otur", "Ale"] },
      { name: "Ambegaon", villages: ["Ghodegaon", "Manchar", "Landewadi"] },
      { name: "Khed", villages: ["Rajgurunagar", "Chakan", "Alandi"] },
    ],
  },
  {
    name: "Raigad",
    talukas: [
      { name: "Alibag", villages: ["Alibag", "Revdanda", "Thal", "Akshi"] },
      { name: "Pen", villages: ["Pen", "Wadkhal", "Nagothane"] },
      { name: "Panvel", villages: ["Panvel", "Kharghar", "Kalamboli", "Kamothe", "Taloja", "Uran"] },
      { name: "Uran", villages: ["Uran", "Nhava", "Sheva"] },
      { name: "Karjat", villages: ["Karjat", "Neral", "Khalapur"] },
      { name: "Khalapur", villages: ["Khalapur", "Khopoli", "Chowk"] },
      { name: "Roha", villages: ["Roha", "Kolad", "Medha"] },
      { name: "Sudhagad", villages: ["Pali", "Sudhagad"] },
      { name: "Mangaon", villages: ["Mangaon", "Goregaon", "Nizampur"] },
      { name: "Tala", villages: ["Tala", "Indapur"] },
      { name: "Shrivardhan", villages: ["Shrivardhan", "Diveagar", "Harihareshwar"] },
      { name: "Mhasla", villages: ["Mhasla", "Goval"] },
      { name: "Mahad", villages: ["Mahad", "Birwadi", "Poladpur"] },
      { name: "Poladpur", villages: ["Poladpur", "Kapade"] },
      { name: "Murud", villages: ["Murud", "Nandgaon", "Kashid"] },
    ],
  },
  {
    name: "Ratnagiri",
    talukas: [
      { name: "Ratnagiri", villages: ["Ratnagiri", "Mirya", "Bhagwati", "Zadgaon"] },
      { name: "Rajapur", villages: ["Rajapur", "Jaitapur", "Dhopeshwar"] },
      { name: "Lanja", villages: ["Lanja", "Veral", "Bhambed"] },
      { name: "Sangameshwar", villages: ["Sangameshwar", "Devrukh", "Sakharpa"] },
      { name: "Chiplun", villages: ["Chiplun", "Sawarda"] },
      { name: "Guhagar", villages: ["Guhagar", "Hedvi", "Velneshwar"] },
      { name: "Khed", villages: ["Khed"] },
      { name: "Dapoli", villages: ["Dapoli", "Harnai", "Anjarle"] },
      { name: "Mandangad", villages: ["Mandangad", "Bankot"] },
    ],
  },
  {
    name: "Sangli",
    talukas: [
      { name: "Miraj", villages: ["Sangli", "Miraj", "Kupwad", "Madhavnagar"] },
      { name: "Tasgaon", villages: ["Tasgaon", "Bhilawadi", "Palus"] },
      { name: "Kavathe Mahankal", villages: ["Kavathe Mahankal", "Dhalgaon"] },
      { name: "Jat", villages: ["Jat", "Umarkhed"] },
      { name: "Khanapur", villages: ["Vita", "Khanapur", "Bhalwani"] },
      { name: "Atpadi", villages: ["Atpadi", "Dighanchi"] },
      { name: "Kadegaon", villages: ["Kadegaon", "Wanghi"] },
      { name: "Palus", villages: ["Palus", "Kundal", "Ramanandnagar"] },
      { name: "Walwa", villages: ["Islampur", "Walwa", "Ashta", "Peth"] },
      { name: "Shirala", villages: ["Shirala", "Kokrud"] },
    ],
  },
  {
    name: "Satara",
    talukas: [
      { name: "Satara", villages: ["Satara", "Koregaon", "Godoli", "Limb"] },
      { name: "Koregaon", villages: ["Koregaon", "Rahimatpur", "Wathar"] },
      { name: "Khatav", villages: ["Vaduj", "Khatav", "Pusesavali"] },
      { name: "Man", villages: ["Mhaswad", "Dahiwadi", "Andhali"] },
      { name: "Phaltan", villages: ["Phaltan", "Barad", "Nimbhore"] },
      { name: "Khandala", villages: ["Khandala", "Lonand", "Shirwal"] },
      { name: "Wai", villages: ["Wai", "Panchgani", "Bavdhan"] },
      { name: "Jaoli", villages: ["Medha", "Bamnoli", "Kelghar"] },
      { name: "Mahabaleshwar", villages: ["Mahabaleshwar", "Panchgani", "Tapola"] },
      { name: "Patan", villages: ["Patan", "Helwak"] },
      { name: "Karad", villages: ["Karad", "Masur", "Umbraj", "Koyananagar"] },
    ],
  },
  {
    name: "Sindhudurg",
    talukas: [
      { name: "Kudal", villages: ["Kudal", "Pinguli", "Mangaon"] },
      { name: "Sawantwadi", villages: ["Sawantwadi", "Amboli", "Banda"] },
      { name: "Vengurla", villages: ["Vengurla", "Redi", "Shiroda"] },
      { name: "Malvan", villages: ["Malvan", "Tarkarli", "Devbag", "Achara"] },
      { name: "Kankavli", villages: ["Kankavli", "Phonda", "Kasarda"] },
      { name: "Devgad", villages: ["Devgad", "Vijaydurg", "Mithbav", "Dabhole", "Dabhol"] },
      { name: "Dodamarg", villages: ["Dodamarg", "Tilari"] },
      { name: "Vaibhavwadi", villages: ["Vaibhavwadi", "Napane"] },
    ],
  },
  {
    name: "Solapur",
    talukas: [
      { name: "Solapur North", villages: ["Solapur", "Hotgi", "Shelgi", "Akkalkot Road"] },
      { name: "Solapur South", villages: ["Mandrup", "Valsang", "Kumbhari"] },
      { name: "Akkalkot", villages: ["Akkalkot", "Maindargi", "Nagansur"] },
      { name: "Barshi", villages: ["Barshi", "Vairag", "Pangri"] },
      { name: "Madha", villages: ["Madha", "Kurduwadi", "Modnimb"] },
      { name: "Karmala", villages: ["Karmala", "Jeur", "Kem"] },
      { name: "Pandharpur", villages: ["Pandharpur", "Gopalpur", "Wakhari"] },
      { name: "Sangola", villages: ["Sangola", "Nazare", "Medshingi"] },
      { name: "Malshiras", villages: ["Malshiras", "Akluj", "Natepute"] },
      { name: "Mangalvedha", villages: ["Mangalvedha", "Maravade"] },
      { name: "Mohol", villages: ["Mohol", "Kurul", "Lamboti"] },
    ],
  },
  {
    name: "Thane",
    talukas: [
      { name: "Thane", villages: ["Thane", "Kalwa", "Mumbra", "Diva", "Ghodbunder"] },
      { name: "Kalyan", villages: ["Kalyan", "Dombivli", "Ambarnath", "Badlapur", "Titwala"] },
      { name: "Ulhasnagar", villages: ["Ulhasnagar", "Vithalwadi", "Shahad"] },
      { name: "Ambarnath", villages: ["Ambarnath", "Badlapur", "Kulgaon"] },
      { name: "Bhiwandi", villages: ["Bhiwandi", "Kon", "Padgha", "Narpoli"] },
      { name: "Murbad", villages: ["Murbad", "Saralgaon", "Tokawade"] },
      { name: "Shahapur", villages: ["Shahapur", "Asangaon", "Vashind"] },
    ],
  },
  {
    name: "Wardha",
    talukas: [
      { name: "Wardha", villages: ["Wardha", "Sindi", "Sevagram", "Waifad"] },
      { name: "Deoli", villages: ["Deoli", "Hamdapur"] },
      { name: "Seloo", villages: ["Seloo", "Nachangaon"] },
      { name: "Arvi", villages: ["Arvi", "Karanja"] },
      { name: "Ashti", villages: ["Ashti", "Rohana"] },
      { name: "Karanja", villages: ["Karanja", "Hingni"] },
      { name: "Hinganghat", villages: ["Hinganghat", "Allipur", "Samudrapur"] },
      { name: "Samudrapur", villages: ["Samudrapur", "Nandori"] },
    ],
  },
  {
    name: "Washim",
    talukas: [
      { name: "Washim", villages: ["Washim", "Kata", "Ansing"] },
      { name: "Malegaon", villages: ["Malegaon", "Jambhrun"] },
      { name: "Risod", villages: ["Risod", "Kenwad"] },
      { name: "Mangrulpir", villages: ["Mangrulpir", "Manora"] },
      { name: "Manora", villages: ["Manora", "Pohara"] },
      { name: "Karanja", villages: ["Karanja", "Kamargaon"] },
    ],
  },
  {
    name: "Yavatmal",
    talukas: [
      { name: "Yavatmal", villages: ["Yavatmal", "Lohara", "Wadgaon"] },
      { name: "Arni", villages: ["Arni", "Jodmoha"] },
      { name: "Babhulgaon", villages: ["Babhulgaon", "Kolgaon"] },
      { name: "Darwha", villages: ["Darwha"] },
      { name: "Digras", villages: ["Digras", "Rui"] },
      { name: "Ghatanji", villages: ["Ghatanji", "Jodmoha"] },
      { name: "Kalamb", villages: ["Kalamb"] },
      { name: "Mahagaon", villages: ["Mahagaon", "Bori"] },
      { name: "Maregaon", villages: ["Maregaon", "Karanji"] },
      { name: "Ner", villages: ["Ner"] },
      { name: "Pandharkawada", villages: ["Pandharkawada"] },
      { name: "Pusad", villages: ["Pusad", "Mulawa", "Umarkhed"] },
      { name: "Ralegaon", villages: ["Ralegaon", "Zadgaon"] },
      { name: "Umarkhed", villages: ["Umarkhed", "Mahagaon"] },
      { name: "Wani", villages: ["Wani", "Kayar", "Mukutban"] },
      { name: "Zari Jamani", villages: ["Zari Jamani", "Patan"] },
    ],
  },
];

function normVillage(v) {
  if (typeof v === "string") return { name: v, post: v };
  const [name, post] = v;
  return { name, post: post || name };
}

const districts = data.map((d) => ({
  name: d.name,
  ...(d.aliases ? { aliases: d.aliases } : {}),
  talukas: d.talukas.map((t) => ({
    name: t.name,
    villages: t.villages.map(normVillage),
  })),
}));

const outPath = path.join(__dirname, "..", "lib", "maharashtra-geo.ts");
const body = `import type { GeoDistrict } from "./types";

/** Maharashtra revenue hierarchy for cascading search filters. */
export const MAHARASHTRA_DISTRICTS: GeoDistrict[] = ${JSON.stringify(districts, null, 2)};

export const DISTRICT_NAMES = MAHARASHTRA_DISTRICTS.map((d) => d.name);
`;

fs.writeFileSync(outPath, body);
const talukas = districts.reduce((n, d) => n + d.talukas.length, 0);
const villages = districts.reduce(
  (n, d) => n + d.talukas.reduce((m, t) => m + t.villages.length, 0),
  0,
);
console.log({ districts: districts.length, talukas, villages, outPath });
